### ISSUE TITLE
Purl spec icon

### ISSUE THREAD

**Issue by SirMaster** [package-url/purl-spec#41] opened 2018-04-19 22:41 UTC
Hi,

We here at Sonatype are building out a new search.maven.org site. We have a BETA running on https://search.maven.org/beta/

Having caught the attention of the purl-spec we have added it to our list of available modules by providing a quick way to get a generated purl.

On our artifacts page we added it as shown below :

![screen shot 2018-04-19 at 3 37 15 pm](https://user-images.githubusercontent.com/3211896/39021855-99f70824-43e7-11e8-9735-15283bbc0379.png)

For a life demo see : https://search.maven.org/beta/artifact/org.springframework.boot/spring-boot/2.0.1.RELEASE/jar

As you might see for the other formats we have a recognizable icon indicating their association. We were wondering if you have anything like that as well to indicate the purl-spec.

**Comment by sschuberth** [comment] 2018-09-17 17:18
Closing this as a duplicate of #19.

**Closed by sschuberth** 2018-09-17 17:18 UTC
