### ISSUE TITLE
Distinction from Persistent URLs (PURLs)

### ISSUE THREAD

**Issue by jmkeil** [package-url/purl-spec#48] opened 2018-08-29 08:14 UTC
Hi, I just came across this project and I like the idea to provide universal identifiers for software packages. However, I would like to express some concerns regarding the name PURL. This name is already used for persistent URLs (see [archive.org](https://archive.org/services/purl/help), [Wikipedia](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator)). I think it is not a good idea to add unambiguousness at one place by introducing new ambiguousness at another place without need.

**Comment by jdillon** [comment] 2019-04-16 01:42
Not sure what the problem is here, Package-URL is the name, PURL is just a way folks talk about it generally.  There are many other cases of duplicated short-names.

**Comment by iamwillbar** [comment] 2019-11-14 23:04
Closing this issue based on @jdillon's explanation.

**Closed by iamwillbar** 2019-11-14 23:04 UTC
