### ISSUE TITLE
Ambiguity between test cases and specification

### ISSUE THREAD

**Issue by althonos** [package-url/purl-spec#40] opened 2018-04-11 13:22 UTC
Hi there,

I'm working on a [Rust module to parse and build purls](https://github.com/althonos/packageurl-rs), it's mostly complete but I do have a question concerning qualifiers order:

* the specification, well, specifies that qualifiers must be added to the purl in lexicographic order 
* in test test case, the `maven uses qualifiers` and `maven pom reference` examples canonical purls do not have qualifiers in the right order

So, is it an error in the test case ? Or do `maven` purls have a special rule for qualifiers ? The same goes for `maven pom reference`: I'm not sure how the canonical purl is supposed to be derived from the purl.

**Comment by althonos** [comment] 2018-04-11 15:01
Besides, there's also an issue with `docker`, since `:` should be encoded but isn't in any version: for instance, `docker:customer/dockerimage@sha256:244fd47e07d1004f0aed9c?repository_url=gcr.io` should probably be `docker:customer/dockerimage@sha256%3A244fd47e07d1004f0aed9c?repository_url=gcr.io` since versions are percent-encoded and `:` should be as well when not used as the type separator.

**Comment by stevespringett** [comment] 2018-08-16 02:30
I believe this is a duplicate of #39

**Closed** 2020-04-01 16:39 UTC
Labels: duplicate
